### PR TITLE
Version 5.2.0

### PR DESCRIPTION
**Pull request by cdgriffith**
* Adding checks for frozen boxes to `pop`, `popitem` and `clear` (thanks to Varun Madiath)
* Fixing requirements-test.txt (thanks to Fabian Affolter)
* Fixing Flake8 conflicts with black (thanks to Varun Madiath)
* Fixing coveralls update (thanks to Varun Madiath)

Co-authored-by: Varun Madiath <vamega@gmail.com>
Co-authored-by: Fabian Affolter <mail@fabian-affolter.ch>

### CODE REVIEW

**Comment by vamega** [comment]
Are you waiting for something to promote/merge this?

**Comment by cdgriffith** [comment]
@vamega Sorry for delay, reformatted recently and my test+deploy script apparently didn't survive so was working on re-creating that, and of course general distractions. (It tests everything on Windows on multiple python versions, so I can make sure no OS dependent errors happen.)

**Comment by vamega** [comment]
No need to apologize, was just curious.
I’d love to look at your test/deploy script or what you’ve managed to
recreate.

Trying to make a template for myself for future Python projects.

**Comment by cdgriffith** [comment]
It's a pretty simple `tox.ini` file and `release.bat`, just need all the python versions setup.  (This release file doesn't have the safety checks to stop in it yet, so I just commented out the upload stuff first round).

```
[tox]
envlist = pyw38,pyw39,pypy37
skip_missing_interpreters=True

[testenv]
commands =
    pip install -r requirements.txt
    pip install -r requirements-test.txt
    pytest

[testenv:pyw38]
basepython =  C:\Python38\python.exe

[testenv:pyw39]
basepython = C:\Python39\python.exe

[testenv:pypy37]
basepython = C:\pypy\pypy3.7-v7.3.2-win32\pypy3.exe
```


```
pip install twine wheel tox
tox
rd /s /q "dist"
rd /s /q "build"
python setup.py build sdist
python setup.py build bdist_wheel
twine check dist/*
twine upload dist/* --config-file .pypirc

```

**Pull request merged**
