### PR TITLE
attempt to add python2.6 support

### PR DESCRIPTION
**Pull request by FooBarQuaxx**

### CODE REVIEW

**Comment by FooBarQuaxx** [comment]
I needed this very nice library used on an internal project that required supporting old linux distributions (unfortunately) still running python 2.6.

**Comment by cdgriffith** [comment]
For this moment I would suggest using Box 2.x, as that does support python 2.6 as long as you don't need any of the Box 3.0 features. 

I will try out some more testing with python 2.6 when I can for the 3.x develop branch with your modifications. If  very large data sets we aren't slowed down much and there aren't large inconveniences, I am ok with making it 2.6 compatible. 

Worst case of it is a lot slower / more painful and you need the 3.x stuff, you may need to maintain your own fork of it, so still not end of world 😄

**Comment by cdgriffith** [comment]
After doing more testing and benchmarking, We can bring back 2.6 support for the next release of Box!  (Will not promise it is something that is maintained if there is a must have feature at some point, but at least this next single release will support it.) 

Fastest 2.6 way I have found is just slightly slower than the dict comprehension (faster than list comp then dicting): 

```python
        out = {}
        for k, v in self._box_config.items():
            if not k.startswith("__"):
                out[k] = v
        return out
```

Code is in https://github.com/cdgriffith/Box/tree/conversion_box_raise_errors branch.

**Comment by cdgriffith** [comment]
@FooBarQuaxx Version 3.1.0 has been re-worked to include Python 2.6 support for you. You have also been added to [Authors](https://github.com/cdgriffith/Box/blob/3.1.0/AUTHORS.rst). Thanks again for your PR and feedback!

**Comment by FooBarQuaxx** [comment]
Thanks.

**Pull request closed without merging**
