### PR TITLE
Version 7.0.0

### PR DESCRIPTION
**Pull request by cdgriffith**
* Adding #169 default functions with the box_instance and key parameter (thanks to Коптев Роман Викторович)
* Adding #170 Be able to initialize with a flattened dict - by using DDBox (thanks to Ash A.)
* Adding #192 box_dots treats all keys with periods in them as separate keys (thanks to Rexbard)
* Adding #211 support for properties and setters in subclasses (thanks to Serge Lu and David Aronchick)
* Adding #226 namespace to track changes to the box (thanks to Jacob Hayes)
* Adding #236 iPython detection to prevent adding attribute lookup words (thanks to Nishikant Parmar)
* Adding #238 allow ``|`` and ``+`` for frozen boxes (thanks to Peter B)
* Adding new DDBox class (Default Dots Box) that is a subclass of SBox
* Fixing #235 how ``|`` and ``+`` updates were performed for right operations (thanks to aviveh21)
* Fixing #234 typos (thanks to Martin Schorfmann)
* Fixing no implicit optionals with type hinting

### CODE REVIEW

**Comment by JacobHayes** [comment]
I'm having some issues with the wheels for python <3.11 ([example](https://github.com/artigraph/artigraph/actions/runs/4050296271/jobs/6967555475#step:6:263)). Looks like the <3.11 wheels (which did not work) are marked x86_64, while the 3.11 wheel (which did work) is marked universal (x86_64 and arm64):
```
python_box-7.0.0rc0-cp37-cp37m-macosx_10_15_x86_64.whl
python_box-7.0.0rc0-cp38-cp38-macosx_10_15_x86_64.whl
python_box-7.0.0rc0-cp39-cp39-macosx_11_0_x86_64.whl
python_box-7.0.0rc0-cp310-cp310-macosx_11_0_x86_64.whl
python_box-7.0.0rc0-cp311-cp311-macosx_10_9_universal2.whl
```

**Comment by cdgriffith** [comment]
@JacobHayes added a new version `7.0.0rc1` that just nixes macos Cython optimized builds for now until there is a good way to make `universal2` packages across supported versions  (tracking in #242)

**Comment by JacobHayes** [comment]
Looks like the install [worked](https://github.com/artigraph/artigraph/actions/runs/4057480974/jobs/6983282189), thanks!

**Comment by JacobHayes** [comment]
Confirming the new extras metadata look good (ie: ruamel is not installed on my side)!

**Pull request merged**
